/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface StencilLayout {
        /**
          * @default 'inverted'
         */
        "variant": 'standard' | 'inverted';
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLStencilLayoutElement extends Components.StencilLayout, HTMLStencilElement {
    }
    var HTMLStencilLayoutElement: {
        prototype: HTMLStencilLayoutElement;
        new (): HTMLStencilLayoutElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "stencil-layout": HTMLStencilLayoutElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface StencilLayout {
        /**
          * @default 'inverted'
         */
        "variant"?: 'standard' | 'inverted';
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "stencil-layout": StencilLayout;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "stencil-layout": LocalJSX.StencilLayout & JSXBase.HTMLAttributes<HTMLStencilLayoutElement>;
        }
    }
}
